# Generated by Django 3.2 on 2022-05-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=30, verbose_name='상호')),
                ('receive_place', models.CharField(max_length=30, verbose_name='배송 희망 위치')),
                ('order_status', models.BooleanField(default=False, verbose_name='펀딩상태')),
                ('target_people', models.PositiveIntegerField(verbose_name='펀딩 희망 인원')),
                ('target_money', models.PositiveIntegerField(verbose_name='펀딩 필요 금액')),
                ('target_time', models.DateTimeField(verbose_name='완료시간')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='수정일')),
            ],
        ),
    ]
